FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y net-tools

# Install dependencies
RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        git \
        cmake \
        build-essential \
        libluajit-5.1-dev \
        libmariadb-dev-compat \
        libboost-date-time-dev \
        libboost-filesystem-dev \
        libboost-system-dev \
        libboost-iostreams-dev \
        libpugixml-dev \
        libgmp-dev \
        libcrypto++-dev \
        libfmt-dev \
        libjsoncpp-dev \
        screen \
        gdb && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Set working dir
WORKDIR /opt/TibiaCore

# Copy everything from current folder into the container
COPY . .

# Build the project
RUN cd compiler && \
    mkdir -p build && cd build && \
    cmake .. && \
    make && \
    cp tfs /opt/TibiaCore/TibiaCore

# Add restart script
COPY restart.sh ./restart.sh
RUN chmod +x ./restart.sh

# Expose ports
EXPOSE 7171
EXPOSE 7172

# Start the server
CMD ["./restart.sh"]